CHANGELOG.md
README.md
octobot_services/__init__.py
requirements.txt

- get_backtesting_service_feed api
- Service feed handling

[Version] v1.0.3

---

CHANGELOG.md
README.md
octobot_services/__init__.py

- WEB_PORT environment constant

[Version] v1.0.4

---

CHANGELOG.md
README.md
octobot_services/__init__.py
requirements.txt

- python-telegram-bot requirement

[Version] v1.0.6

---

CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/interfaces/util/util.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/178

update backtesting import 

---

CHANGELOG.md
README.md
octobot_services/__init__.py
requirements.txt

[Version] v1.1.2

---

CHANGELOG.md
README.md
octobot_services/__init__.py
requirements.txt

- Channel requirement
- Commons requirement
- Trading requirement

[Version] v1.1.3

---

CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/interfaces/bots/abstract_bot_interface.py
octobot_services/service_feeds/abstract_service_feed.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/73

Improve stop

---

CHANGELOG.md
README.md
octobot_services/__init__.py
requirements.txt

[Version] v1.1.5

---

CHANGELOG.md
Makefile
README.md
octobot_services/__init__.py
requirements.txt

[Version] v1.1.6 

---

CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/interfaces/bots/abstract_bot_interface.py
octobot_services/interfaces/util/trader.py
octobot_services/interfaces/util/util.py

requires https://github.com/Drakkar-Software/OctoBot/pull/1203

Run in bot async executor

---

.travis.yml
CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/api/interfaces.py
octobot_services/api/notification.py
octobot_services/consumers/__init__.py
octobot_services/consumers/octobot_channel_consumer.py
octobot_services/interfaces/abstract_interface.py
octobot_services/notifier/abstract_notifier.py
octobot_services/util/exchange_watcher.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/218

initialize through octobot channel

---

CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/interfaces/bots/abstract_bot_interface.py
octobot_services/interfaces/interface_factory.py
octobot_services/notifier/notifier_factory.py
octobot_services/service_feeds/service_feed_factory.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/88

Remove advanced manager

---

CHANGELOG.md
README.md
octobot_services/__init__.py
requirements.txt

[Version] v1.1.13

---

octobot_services/notifier/abstract_notifier.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/250
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/242 (version)

update channel subscribe import

---

CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/services/abstract_service.py

fixes https://github.com/Drakkar-Software/OctoBot-Services/issues/53
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/268

Fix web config error

---

CHANGELOG.md
README.md
octobot_services/__init__.py
requirements.txt

[Version] v1.1.17

---

CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/interfaces/bots/abstract_bot_interface.py
octobot_services/interfaces/util/portfolio.py
octobot_services/interfaces/util/trader.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/293

replace real trader refresh by portfolio refresh

---

CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/notifier/abstract_notifier.py
requirements.txt

- Requirements
Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/292

[Version] v1.1.19

---

CHANGELOG.md
README.md
octobot_services/__init__.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/308

[Version] v1.1.20

---

CHANGELOG.md
README.md
octobot_services/__init__.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/142

[Version] v1.2.7

---

CHANGELOG.md
README.md
octobot_services/__init__.py
setup.py

Signed-off-by: Herklos <herklos.dev@protonmail.com>

Add python3.9 to supported version

---

CHANGELOG.md
README.md
octobot_services/__init__.py
requirements.txt

fixes:
Error when receiving Google feed: ('ClientResponse' object has no attribute 'status_code') (AttributeError)

[Version] v1.2.18

---

CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/services/service_factory.py
requirements.txt

replace missing config warning by info log

---

octobot_services/interfaces/util/portfolio.py
requirements.txt

Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/656

[Util][Portfolio] Migrate to assets

---

requirements.txt

Described in https://github.com/LonamiWebs/Telethon/issues/3215
Reported in https://github.com/Drakkar-Software/OctoBot/issues/1901

[Telegram] Fix RPC login error

---

CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/api/notification.py
octobot_services/enums.py
octobot_services/interfaces/__init__.py
octobot_services/interfaces/util/__init__.py
octobot_services/interfaces/util/position.py
octobot_services/notification/formated_notifications.py
octobot_services/notification/notification.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/695

Add positions

---

CHANGELOG.md
README.md
octobot_services/__init__.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/704

bump requirements

---

CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/interfaces/util/order.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/778

[Orders] don't wait for exchange full cancel in interface cancel api

---

CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/interfaces/util/order.py
octobot_services/interfaces/util/trader.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/846
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/848

[Orders] Handle cancel error

---

CHANGELOG.md
README.md
octobot_services/__init__.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/342

[Version] v1.5.1

---

CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/notifier/abstract_notifier.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/884

[Orders] add update_type to channel

---

CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/notification/formated_notifications.py
octobot_services/notifier/abstract_notifier.py

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1076

Order notif

---

octobot_services/interfaces/bots/abstract_bot_interface.py

requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/465

[time] add local_timezone to get_command_ping

---

CHANGELOG.md
README.md
octobot_services/__init__.py
octobot_services/interfaces/util/order.py
requirements.txt

requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/1265

Signal dep
